### ISSUE TITLE
Design notes for beta

### ISSUE THREAD

**Issue by beckyrother** [zooniverse/scribes-of-the-cairo-geniza#66]
Using this issue to record design notes before we go to beta. 

_These notes are from the 4/30 version of scribesofthecariogeniza.org_

- [x] Deletion / Insertion tags: the `/` should be on the left-side tag, not the right
- [x] Save button?
- [x] Add more space under `Name and Attribution` section:
<img width="510" alt="scribes_from_the_cairo_geniza" src="https://user-images.githubusercontent.com/1392130/39449305-4b1e2fda-4c8d-11e8-9622-8b0ee037747f.png">

- [x] All modals have a weird not-black shadow color. Should be `rgba(0,0,0,0.29)`
- [x] Close Annotation modal is awkward language when deleting an empty transcription. Is this necessary? 

<img width="443" alt="scribes_from_the_cairo_geniza" src="https://user-images.githubusercontent.com/1392130/39449425-9c3b3502-4c8d-11e8-8909-90729d229530.png">

- [ ] When collapsing the right-side info box, the box should collapse all the way after it's been clicked. Only after the user has moved outside of the collapsed sidebar and then back onto it should it pop out a little

- [x] I like the X hover state on the Crib Sheet – can this be everywhere?

<img width="183" alt="pasted_image_4_30_18__3_50_pm" src="https://user-images.githubusercontent.com/1392130/39449639-34de768e-4c8e-11e8-9ee6-e20b728f8fc7.png">

**Comment by shaunanoordin** [comment]
@beckyrother 

- ❓  _"Deletion / Insertion tags" :_ do you mean we should have Option 1 or Option 2? Sorry, the context of what's "left" and "right" completely go out the window once we have RtL text.

![screen shot 2018-05-01 at 15 35 55](https://user-images.githubusercontent.com/13952701/39476922-8eea23fe-4d55-11e8-8453-b783c9da4b24.png)
Option 1

![screen shot 2018-05-01 at 15 38 13](https://user-images.githubusercontent.com/13952701/39476958-b0ea457e-4d55-11e8-9913-d613d1415ebb.png)
Option 2

I _was_ going to make a joke about port and starboard, but let's not confuse this any further.

- _"Save button" :_ are you asking where's the "Save Progress" button? It should only appear when the user is logged in. ~~Please let me know if you still don't see it.~~ (EDIT: OH goddamn no wonder you couldn't see it, the production version doesn't have the Zooniverse App ID that would allow logging in. OK, that should be fixed shortly.)

- _"Add more space after the Name+Attribution section" :_ OK, there's be more space right above the "Show cribsheet" button

- ❓ _"All modals have a weird not-black shadow color" :_ to be clear, we're talking about modals like the tutorial, and we're talking about the CSS box shadow, right? OK, I can change it to `rgba(0,0,0, 0.29)` , though the low opacity makes it somewhat similar to the current `#b4b4b4` on my computer monitor. To be safe, I present to you three options:

![screen shot 2018-05-01 at 15 47 50](https://user-images.githubusercontent.com/13952701/39477459-4ca9d744-4d57-11e8-9fd4-0c1720804b3b.png)
Option 1: the current `#b4b4b4`. This is just for comparison.

![screen shot 2018-05-01 at 15 48 25](https://user-images.githubusercontent.com/13952701/39477475-52ca3312-4d57-11e8-8b8b-40edf08a8f99.png)
Option 2: the box shadow colour, set to the `rgba(0,0,0, 0.29)` you requested (by default, I will make this change)

![screen shot 2018-05-01 at 15 48 38](https://user-images.githubusercontent.com/13952701/39477501-5f15c7f8-4d57-11e8-8b04-5c207b1041bd.png)
Option 3: just a solid `#000` - the reason I wanted to check is because I'm not sure if the 10px CSS "shadow diffusion" already accounts for the 0.29 opacity.

- _"Close Annotation Dialogue is awkward, do we need it?" :_ 🤔 

- _"When collapsing the right-side info box, the box should collapse all the way after it's been clicked" :_ Uh, I'll need to look into this - the reason the box "peeks out" when it's been collapsed is because the mouse cursor is still hovering over the collapsed menu when it closes, so it's two conflicting commands ("collapse" and "peek out") taking place at once. Might be tricky to solve, so I might need to bump this farther down the ToDo list, sorry in advance.

- _"X hover state, everywhere, just everywhere" :_ OK

**Comment by beckyrother** [comment]
@shaunanoordin Shaun++ thank you!!

- Deletion/Insertion tags: Please go with Option 2

- Modal shadows: While in some places the grey #b4b4b4 looks the same, on dark backgrounds it's a distracting light grey. Please go with Option 2 – solid #000 is a bit too harsh.  

- Close annotation dialog: on re-reading it, maybe it's just the second sentence that is confusing to me. How do we feel about just removing the second sentence? 

- Right-side info box: Totally makes sense, it's fine to push this


Thanks again!!!

**Comment by beckyrother** [comment]
Here's a random thing: Can we remove the "scroll down to start transcribing" link on the home page?

**Comment by snblickhan** [comment]
@shaunanoordin 

> ❓ "Deletion / Insertion tags" : do you mean we should have Option 1 or Option 2? Sorry, the context of what's "left" and "right" completely go out the window once we have RtL text.

Option 2, please!

**Comment by snblickhan** [comment]
HOME PAGE
- [ ] Add all logos to home page (not just research partners)

- [ ] @beckyrother does "PARTNER INSTITUTIONS" text need to be centered?

ABOUT PAGE
- [ ] About the Project header at top + subsection link

- [ ] Images smaller -- fit heightwise instead of widthwise

- [ ] "Now we are at the point of the transcription phase, or Phase **II.The** goal of PHase II is to:" <- needs space

- [ ] Add Bodleian library bio -- text [here](https://docs.google.com/document/d/1yHDymq8EUUWVOkwI6YNKiSt0PnE-hAl5p8Cl5T0E0Rs/edit?ts=5ae36b3e)

- [ ] Add Bodleian logo to RH once text is added

- [ ] Add WIll & Shaun to team bios -- text [here], photos coming from Zooniverse bios (https://docs.google.com/document/d/1OZItGCeIodopuCEpaaFsmDNCuP3VoQ-fuj7uqiEqnSE/edit)

TUTORIAL

- [ ] Tutorial steps are too wide (check width of tutorial-step class)

**Comment by beckyrother** [comment]
New About page design: https://invis.io/Y6DLOTUNE#/254604074_SotCG-About

**Comment by beckyrother** [comment]
@snblickhan "Partner institutions" label is intentional, but if it's awkward it can certainly be centered.

**Comment by snblickhan** [comment]
@beckyrother 100% up to you. Just checking.

**Comment by wgranger** [comment]
HEADER
[ ] Add link paths to "talk" and "collect" on project header

**Comment by beckyrother** [comment]
- [ ] Tutorial: Please use the same style as in the field guide for the text here:
<img width="426" alt="scribes_of_the_cairo_geniza" src="https://user-images.githubusercontent.com/1392130/39590469-99d7fc10-4ec6-11e8-8953-dee162f29d1e.png">

- [ ] Home: "Coming soon" should be on a separate line to the button:
<img width="398" alt="scribes_of_the_cairo_geniza" src="https://user-images.githubusercontent.com/1392130/39590499-b23aefce-4ec6-11e8-9c7c-466e9412c167.png">
