### ISSUE TITLE
No prompt to continue saved work

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#78]
When I save work, the timestamp is generated, but when I log out & return, the interface doesn't prompt me to continue my work.

**Comment by shaunanoordin** [comment]
## Issue Report
When a user Saves Progress, then **closes the browser window/browser tab,** then reloads the website, they no longer see the Resume Progress prompt.

### Investigation
Testing has confirmed - on OSX+Chrome66, commit 71e7771 - that this issue exists. The key here is that the _closing of the browser window/tab._ If a user _doesn't_ close the window/tab and reloads the page, the Resume Progress prompt appears as expected.

**Testing steps:**
- Go to scribesofthecairogeniza.org/classify
- Login.
- Make an annotation on the Classifier page.
- Click Save Progress.
- Close the window/tab. (NOTE: if doing this on an Incognito window, please don't close all windows - you'll lose essential information stored in localStorage.)
- Open scribesofthecairogeniza.org/classify in a new window/tab
- EXPECTED: Resume Progress prompt appears.
- ACTUAL: No Resume Progress prompt appears.

**Diagnosis:**
- The problem is that when the browser window/tab is closed, the user becomes **logged out** (???)
- This means the app can't see the user's saved progress, because it thinks the user is now an anonymous user.
- The user has to click on the Sign In button again to be re-logged in (without having to actually go to the Sign In form... indicating some quirks with the session storage AND/OR local storage.)
- @eatyourgreens, do you know if this `panoptes-client` working as expected? My guess is that the `panoptesClientOAuth_tokenDetails` data is stored in _sessionStorage,_ which doesn't carry between new windows/tabs.
  - Also, for comparison - lab.wildcamgorongosa.org _doesn't_ care if you access it in a new window, it remembers if you're logged in... it uses PJC 2.8.0 and I don't note any data stored in sessionStorage. Could it be a new security feature added in 2.9.0+? (Wait, how does 2.8.0 even work, wtf)

**Notes**
- This issue actually occurs with **Anti-Slavery Manuscripts** too, but the Save/Resume Progress issue isn't noticeable there because the Classifier prompt **keeps reminding users to login before they can even do anything.**
- This issue can be seen very simply - open the Scribes or ASM website. Login. Open a new window/tab. Notice that you're not logged in. Click the Sign In button, and you'll notice that you're now signed in to Scribes/ASM without having to type in your details. So _Panoptes_ remembered you're still sign in, but the Scribes/ASM website needed a reminder between new windows.

**Possible Solution**
- Option 1: The Classifier Page could prompt users to login.
  - Pro: relatively the most realistic solution to implement.
  - Con: might interfere with Workflow selection logic. That bit of code is a bit twisty.
  - Con: Forcing users to login when not strictly necessary (i.e., we're not testing splits)... not sure if that's good or bad.
- Option 2: Figure out what's happening with the PJC, determine if behaviour is intended, and if not, fix it.

### Status
Problem identified, solution required. Significant priority.

**Comment by eatyourgreens** [comment]
@shaunanoordin if third-party cookies are allowed, then you should be able to call [`oauth.checkCurrent()`](https://zooniverse.github.io/panoptes-javascript-client/#panoptes-javascript-client-oauth-oauthcheckcurrent) to get the current user session, without explicitly signing in.

If third party cookies are blocked, the browser has to physically visit panoptes.zooniverse.org to get the current session token (or a login form if there's no valid token.)

We could save the current token in local storage, so that it's available across tabs. It might require some extra code in the client to invalidate expired tokens, since local storage persists forever. At the moment, we rely on session storage deleting the token when you shut down the browser.

**Comment by eatyourgreens** [comment]
Having said that, I have no idea how PFE automatically logs you in _and_ sets Auth headers properly so you can make authenticated API requests. Looking at the code for `checkCurrent`, as far as I can tell, it only returns the currently logged-in user from Panoptes.

**Comment by eatyourgreens** [comment]
zooniverse/panoptes-javascript-client#90
