### ISSUE TITLE
Record keyboard script used during transcription

### ISSUE THREAD

**Issue by snblickhan** [zooniverse/scribes-of-the-cairo-geniza#96]
Note: for Hebrew workflows only.

The research team would like to know which script type (the options that can be set as the keyboard: Ashkenazi Square, etc.) is being used in the keyboard for each individual transcription.

There are a few options for this:
1. Record what keyboard was selected _at the time the entire classification was completed_ (i.e. the last keyboard selection used before submitting).
2. Record which keyboard was used _for each line_ of a transcription (this could be helpful for documents featuring multiple script types, but may not be necessary if it's going to be a lot of work).
3. If possible, also record whether keyboard was open or closed (to see % of volunteers who are typing from their own keyboard).

**Comment by wgranger** [comment]
My inclination (since we don't have GA on this project) is to record options one and three with the classification metadata. I think the second option would be overkill without GA, and it would cause a huge JSON blob to be sent for some messy data along with the classification. 

I'm going to code and push up a solution for the first and third options now to confirm for sure Panoptes doesn't reject this info being sent with the metadata.
